
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk


    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
          - m2-{{ checksum "pom.xml" }}
          - m2-

      - run: mvn package

      - save_cache:
          paths:
            - ~/.m2
          key: m2-{{ checksum "pom.xml" }}